databases:
  - name: jira-db
    databaseName: jira
    user: lm

services:
  - type: web
    name: fastapi-service
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ADMIN_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: jira-db
          property: connectionString
