databases:
  - name: jira-db
    databaseName: jira
    user: lm

services:
  - type: web
    runtime: docker
    name: my-fastapi-app
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ADMIN_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: jira-db
          property: connectionString
