databases:
  - name: jira-db
    databaseName: jira
    user: lm

services:
  - type: web
    name: fastapi-service
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ADMIN_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: jira-db
          property: connectionString
