"""added comments and ticket column detail

Revision ID: 60cd34469110
Revises: c8f86b1fe416
Create Date: 2025-07-20 12:46:29.103801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60cd34469110'
down_revision: Union[str, None] = 'c8f86b1fe416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'), nullable=True))
    op.add_column('tickets', sa.Column('story_points', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('assignee_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['assignee_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'assignee_id')
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'story_points')
    op.drop_column('tickets', 'priority')
    # ### end Alembic commands ###
